obj-m := kvm.o kvm-intel.o
kvm-objs := kvm_main.o x86.o mmu.o emulate.o irq.o i8259.o pmu.o \
	 lapic.o ioapic.o preempt.o i8254.o coalesced_mmio.o irq_comm.o \
	 eventfd.o compat-x86.o async_pf.o cpuid.o irqchip.o mtrr.o \
	 ../external-module-compat.o hyperv.o page_track.o debugfs.o
ifeq ($(CONFIG_KVM_VFIO),y)
kvm-objs += vfio.o
endif
kvm-intel-objs := vmx.o pmu_intel.o vmi.o

kvm-objs += ../refcount.o ../srcu.o ../swait.o

CFLAGS_kvm_main.o = -DKVM_MAIN
